#Augusto correa

### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
Content-Type: application/json

{
    "nome" : "Augusto Correa",
    "cpf" : "01317714975",
    "telefone" : "11999999999"
}

### Verbo PUT – atualizar
PUT  http://127.0.0.1:8000/cliente/1 HTTP/1.1
Content-Type: application/json

{
    "nome" : "Augusto Dos Santos Correa",
    "cpf" : "12345678900",
    "telefone" : "11999999999"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1